services:
  - type: web
    name: frescoop-cif
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOKEN_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
      - key: FRESCOOP_HOST
        value: "0.0.0.0"
